name: teste
description: A sample "Hello, World!" Functions Framework project.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  functions_framework: ^0.4.1
  shelf: ^1.1.4
  shelf_router: ^1.0.0

dev_dependencies:
  shelf_router_generator: 1.0.0  
  build_runner: ^2.0.5
  functions_framework_builder: ^0.4.2
  http: 0.13.3
  test: 1.17.9
  test_process: ^2.0.0
